[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "1337"
APP_KEYS = "toBeSetInDashboard"
API_TOKEN_SALT = "toBeSetInDashboard"
ADMIN_JWT_SECRET = "toBeSetInDashboard"
JWT_SECRET = "toBeSetInDashboard"
DATABASE_CLIENT = "postgres" 